ref = ['temperature_2m', 'dewpoint_temperature_2m', 'u_component_of_wind_10m',
       'v_component_of_wind_10m', 'surface_net_solar_radiation_sum',
       'total_evaporation_sum', 'surface_pressure', 'total_precipitation_sum',
       'SensorZenith', 'SensorAzimuth', 'SolarZenith', 'SolarAzimuth',
       'sur_refl_b01', 'sur_refl_b02', 'sur_refl_b03', 'sur_refl_b04',
       'sur_refl_b05', 'sur_refl_b06', 'sur_refl_b07', 'Clouds', 'LE_PM',
       'NDVI', 'EVI', 'GNDVI', 'SAVI', 'ARVI', 'temperature_2m_rol_30',
       'temperature_2m_rol_7', 'temperature_2m_min', 'temperature_2m_max',
       'temperature_2m_std', 'dewpoint_temperature_2m_rol_30',
       'dewpaoint_temperature_2m_rol_7', 'dewpoint_temperature_2m_min',
       'dewpoint_temperature_2m_max', 'dewpoint_temperature_2m_std',
       'u_component_of_wind_10m_rol_30', 'u_component_of_wind_10m_rol_7',
       'u_component_of_wind_10m_min', 'u_component_of_wind_10m_max',
       'u_component_of_wind_10m_std', 'v_component_of_wind_10m_rol_30',
       'v_component_of_wind_10m_rol_7', 'v_component_of_wind_10m_min',
       'v_component_of_wind_10m_max', 'v_component_of_wind_10m_std',
       'surface_net_solar_radiation_sum_rol_30',
       'surface_net_solar_radiation_sum_rol_7',
       'surface_net_solar_radiation_sum_min',
       'surface_net_solar_radiation_sum_max',
       'surface_net_solar_radiation_sum_std', 'total_evaporation_sum_rol_30',
       'total_evaporation_sum_rol_7', 'total_evaporation_sum_min',
       'total_evaporation_sum_max', 'total_evaporation_sum_std',
       'surface_pressure_rol_30', 'surface_pressure_rol_7',
       'surface_pressure_min', 'surface_pressure_max', 'surface_pressure_std',
       'total_precipitation_sum_rol_30', 'total_precipitation_sum_rol_7',
       'total_precipitation_sum_min', 'total_precipitation_sum_max',
       'total_precipitation_sum_std', 'LE_PM_rol_30', 'LE_PM_rol_7',
       'LE_PM_min', 'LE_PM_max', 'LE_PM_std', 'doy', 'lat', 'lon', 'IGBP',
       'year']